name: Ruby

on:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/6.1.gemfile
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.6
          bundler-cache: true
      # Disabled since it requires access not granted by GitHub Actions for PRs
      # - name: Danger
      #   if: ${{ github.event_name == 'pull_request' }}
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     bundle exec danger
      - name: Rubocop
        run: bundle exec rubocop --autocorrect
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ '3.2', '3.1', '3.0', 'ruby-head' ]
        gemfile: [ '7.1', '7.0', '6.1', 'edge' ]
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
  Demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: demo
          bundler-cache: true
      - name: Run tests
        working-directory: demo
        run: bundle exec rake test:all
